version: '3.3'
networks:
  service_network:
    name: backend
    #driver: custom-driver
    #    driver_opts:
#      custom-driver
services:
  db:
    image: mysql:5
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'PiDash'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "pidashservice"
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password1234@!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password1234@!'
      #default-authentication-plugin: mysql_native_password
    networks:
      - service_network
    #    ports:
      # <Port exposed> : <MySQL Port running inside container>
      #      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  pidash:
    build: .
    ports:
      - '4656:4656'
    expose:
      - '4656'
    networks:
      - service_network
# Names our volume
volumes:
  my-db:
